AWSTemplateFormatVersion: '2010-09-09'
Description: Simple AWS S3 Bucket
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: my-unique-simple-aws-bucket-name