AWSTemplateFormatVersion: '2010-09-09'
Description: Simple AWS S3 Bucket and DynamoDB Table
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketName: my-unique-simple-aws-bucket-name
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MySimpleAWSTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
